name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
    - name: Instrument code
      uses: AryazE/auto-dylin/instrument@main
      with:
        analysis-coverage: false
    - name: Run tests
      run: pytest -W error
    - name: Report results
      uses: AryazE/auto-dylin/report@main
